Nfc writer
T3-FindIt/FindIt pull request #109
Opened 2023-05-30 11:56 UTC by GharibGharib

### Changes / Veranderingen

### Checklist

- [ ] The code has test coverage / De code heeft test dekking
- [ ] The code is documented / De code is gedocumenteerd
- [ ] The code is linted / De code is gelint
- [ ] The code is tested / De code is getest

### Issue

**Issue:** closes #

2023-05-30 12:08 UTC, TomVer99 requested changes
PR heeft 0 info, vul dit in.

2023-05-30 12:31 UTC, NathanThus reviewed
Lot's of magic numbers.

2023-05-30 12:31 UTC, NathanThus commented on Source/NFC-Writer/src/MFRC522Writer.cpp
> +    byte blockAddr4 = 4;
No. So much no.

2023-05-30 12:31 UTC, NathanThus commented on Source/NFC-Writer/src/MFRC522Writer.cpp
> +    char inputString[maxMessageLength] = "";
Why.

2023-05-30 12:31 UTC, NathanThus commented on Source/NFC-Writer/src/UI.cpp
> +    char messagetemp[1000] = "";
WHY.

2023-05-30 12:31 UTC, NathanThus commented on Source/NFC-Writer/src/UI.cpp
> +    unsigned int message_pos = 0;
???

2023-05-30 12:32 UTC, NathanThus requested changes
Making these changes mandatory.

2023-05-30 12:42 UTC, TomVer99 commented on Source/NFC-Writer/src/MFRC522Writer.cpp
> +    mfrc522 = nfc;
Gebruik init list.

2023-05-30 12:45 UTC, TomVer99 commented on Source/NFC-Writer/src/MFRC522Writer.cpp
> +    if (Transfer(dataBuffer, blockAddr4) == -1)
Kunnen deze if statements samen?

2023-05-30 12:46 UTC, TomVer99 commented on Source/NFC-Writer/src/MFRC522Writer.cpp
> +    if (!GetCardAvailable())
If statements kunnen samen?

2023-06-06 12:20 UTC, TomVer99 requested changes
Have you implemented any feedback from the last time?

2023-06-13 08:17 UTC, NathanThus commented on Source/NFC-Writer/src/MFRC522Writer.cpp
> +    char inputString[maxMessageLength] = "";
Why do you need two input strings?

2023-06-13 08:28 UTC, NathanThus requested changes

2023-06-13 08:28 UTC, NathanThus commented on Source/NFC-Writer/src/MFRC522Writer.cpp
> +    byte dataBufferBlock5[bufferSizeBlock5] = "";
Why do you need so many blocks?

2023-06-13 08:28 UTC, NathanThus commented on Source/NFC-Writer/src/UATRInterface.cpp
> +    message[0] = '\0';
Why are you immediately setting [0] to '\0'

2023-06-13 11:26 UTC, NathanThus approved these changes

2023-06-13 11:26 UTC, NathanThus commented
Decent enough. I'll allow it through due to time crunch, but keep in mind what I said about code styling @GharibGharib

2023-06-13 11:27 UTC, merged